# Generated by Django 2.2.3 on 2019-11-10 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(help_text='Enter Name of the Contractor', max_length=100, unique=True)),
                ('address', models.CharField(help_text='Enter address of the Contractor', max_length=512)),
                ('email', models.EmailField(help_text='Enter e-mail of the Contractor', max_length=254, unique=True)),
                ('mobile', models.CharField(help_text='Enter mobile number of the Contractor', max_length=50)),
            ],
            options={
                'ordering': ['contractor_name'],
            },
        ),
        migrations.CreateModel(
            name='PE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe_name', models.CharField(help_text='Enter PE Name', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subproject_name', models.CharField(help_text='Enter Name of the Sub-Project', max_length=100, unique=True)),
                ('district_name', models.CharField(default='n/a', help_text='Enter Name of the District', max_length=100)),
                ('area', models.IntegerField(default=0, help_text='Enter Area of the Sub-project')),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(help_text='Enter Type of the Work', max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_no', models.CharField(help_text='Enter the Package Number', max_length=50, unique=True)),
                ('package_name', models.CharField(help_text='Enter the package name', max_length=1500)),
                ('estimate_value', models.DecimalField(decimal_places=2, default=0, help_text='Enter the estimated value', max_digits=12)),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, help_text='Enter the contract prince', max_digits=12)),
                ('variation_value', models.DecimalField(decimal_places=2, default=0, help_text='Enter variation price (if any)of the contract', max_digits=12)),
                ('contractor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rncontractor', to='package_app.Contractor')),
                ('pe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rnpe', to='package_app.PE')),
                ('sub_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rnsubproject', to='package_app.Subproject')),
                ('works', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rnworks', to='package_app.Works')),
            ],
            options={
                'ordering': ['sub_project', 'works', 'package_no'],
            },
        ),
        migrations.CreateModel(
            name='PackageDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField(blank=True, help_text='Enter the Anual Procurment Plan approval date', null=True)),
                ('ift_date', models.DateField(blank=True, help_text='Enter the IFT date', null=True)),
                ('opening_date', models.DateField(blank=True, help_text='Enter the tender opening date', null=True)),
                ('evaluation_submission_date', models.DateField(blank=True, help_text='Enter the Evaluation Report submission date', null=True)),
                ('evaluation_approval_date', models.DateField(blank=True, help_text='Enter the Evaluation report approval date', null=True)),
                ('adb_concurrence_date', models.DateField(blank=True, help_text='Enter the ADB concurrence date', null=True)),
                ('noa_date', models.DateField(blank=True, help_text='Enter the Notifcation of Award issuing date', null=True)),
                ('contract_sign_date', models.DateField(blank=True, help_text='Enter the tender submission date', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Enter the Work Starting date as per work order', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Enter the Work Completion date as per work order', null=True)),
                ('end_date_extension', models.DateField(blank=True, help_text='Enter the completion date as per time extension(if any)', null=True)),
                ('end_date_actual', models.DateField(blank=True, help_text='Enter the Actual completion date', null=True)),
                ('package_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rnpackages', to='package_app.Packages')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField(blank=True, help_text='Enter the Actual Bill payment date', null=True)),
                ('bill_amount', models.FloatField(default=0, help_text='Enter the amount of the bill')),
                ('FY', models.CharField(default='xxxx-xxxx', help_text='Enter the Package Number', max_length=9)),
                ('bill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package_app.BillName')),
                ('package_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rnbill', to='package_app.Packages')),
            ],
            options={
                'ordering': ['bill_type'],
            },
        ),
    ]
