# Generated by Django 2.2.3 on 2020-01-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0016_auto_20191119_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileup',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
